// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// CppS
double CppS(int n, NumericMatrix Kz, NumericVector Wz, NumericMatrix Kyz, NumericVector Wyz, List L);
RcppExport SEXP _cBall_CppS(SEXP nSEXP, SEXP KzSEXP, SEXP WzSEXP, SEXP KyzSEXP, SEXP WyzSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Kz(KzSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wz(WzSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Kyz(KyzSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wyz(WyzSEXP);
    Rcpp::traits::input_parameter< List >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(CppS(n, Kz, Wz, Kyz, Wyz, L));
    return rcpp_result_gen;
END_RCPP
}
// rowcolsampler
NumericMatrix rowcolsampler(NumericMatrix A, NumericVector s);
RcppExport SEXP _cBall_rowcolsampler(SEXP ASEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(rowcolsampler(A, s));
    return rcpp_result_gen;
END_RCPP
}
// resample
NumericVector resample(int n, NumericMatrix Kz, NumericVector Wz, NumericMatrix Kyz, NumericVector Wyz, List L, NumericMatrix Pi);
RcppExport SEXP _cBall_resample(SEXP nSEXP, SEXP KzSEXP, SEXP WzSEXP, SEXP KyzSEXP, SEXP WyzSEXP, SEXP LSEXP, SEXP PiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Kz(KzSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wz(WzSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Kyz(KyzSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wyz(WyzSEXP);
    Rcpp::traits::input_parameter< List >::type L(LSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Pi(PiSEXP);
    rcpp_result_gen = Rcpp::wrap(resample(n, Kz, Wz, Kyz, Wyz, L, Pi));
    return rcpp_result_gen;
END_RCPP
}
// kernel
double kernel(double x, double h);
RcppExport SEXP _cBall_kernel(SEXP xSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel(x, h));
    return rcpp_result_gen;
END_RCPP
}
// fun2
int fun2(NumericVector x);
RcppExport SEXP _cBall_fun2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fun2(x));
    return rcpp_result_gen;
END_RCPP
}
// eu
double eu(NumericVector x, NumericVector y);
RcppExport SEXP _cBall_eu(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(eu(x, y));
    return rcpp_result_gen;
END_RCPP
}
// dist_cpp
NumericMatrix dist_cpp(NumericMatrix X);
RcppExport SEXP _cBall_dist_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(dist_cpp(X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cBall_CppS", (DL_FUNC) &_cBall_CppS, 6},
    {"_cBall_rowcolsampler", (DL_FUNC) &_cBall_rowcolsampler, 2},
    {"_cBall_resample", (DL_FUNC) &_cBall_resample, 7},
    {"_cBall_kernel", (DL_FUNC) &_cBall_kernel, 2},
    {"_cBall_fun2", (DL_FUNC) &_cBall_fun2, 1},
    {"_cBall_eu", (DL_FUNC) &_cBall_eu, 2},
    {"_cBall_dist_cpp", (DL_FUNC) &_cBall_dist_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_cBall(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
