# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CppS <- function(n, Kz, Wz, Kyz, Wyz, L) {
    .Call(`_cBall_CppS`, n, Kz, Wz, Kyz, Wyz, L)
}

